### ISSUE TITLE
`nanorand::gen::RandomRange::random_range(lower, upper)` behaves incorrectly (`upper` is non-inclusive)

### ISSUE THREAD

**Issue by spitfire05** [aspenluxxxy/nanorand-rs#21]
`WyRand::new().generate_range::<u32>(0, 1);` seems to always return `0`, while the common understanding is that the `upper` parameter should be inclusive.

This seems to be the understanding of the crate's author as well, as in `shuffle` implementation:

```
fn shuffle<I, S: AsMut<[I]>>(&mut self, mut target: S) {
		let target = target.as_mut();
		let target_len = target.len();
		for idx in 0..target_len {
			let random_idx = self.generate_range::<usize>(0, target_len - 1);
			target.swap(idx, random_idx);
		}
	}
```

`target_len - 1` basically means the last value in slice will never be selected as swap target, leading to some bizarre behavior, like shuffling a slice of len 2 always returns reversed slice, instead of giving roughly 50/50 distribution of original and reversed.

If the `upper` parameter was indeed meant to be non-inclusive, then I guess the docs should be updated and `shuffle` implementation fixed. If it was not, then the `generate_range` function has to be fixed.

Tested on crate v 0.5.2, Rust 1.48.0

EDIT: typos, formatting

**Comment by aspenluxxxy** [comment]
I believe this has been solved in https://github.com/aspenluxxxy/nanorand-rs/commit/7e1704e6a80697b7b4bda4d93a8a476748379463

**Comment by spitfire05** [comment]
This is still broken as of `nanorand 0.5.2`.

`rng.generate_range::<u64>(0, 1)` still returns only `0`, and so `rng.shuffle()` for 2-element vectors always returns the same (reversed) order.
